spring:
  application:
    name: shortJ-prod
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:3306}/${POSTGRES_DB:shortJ_db}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      flush: ${REDIS_FLUSH:true}

server:
  port: 8081

short-url:
  allowed-chars: ${ALLOWED_CHARS:abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789}
  key-length: ${SHORT_URL_LENGTH:6}
  std-expiration-minutes: ${STD_EXPIRATION_MINUTES:60}
  hash-salt-secret: ${HASH_SALT_SECRET:my-secret-salt-for-development}

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html